### ISSUE TITLE
Feature request: remove DOM dependencies

### ISSUE THREAD

**Issue by dragGH102** [eddflrs/meteor-ddp#10]
As the title says, 

specifically jQuery dependency.
Otherwise it doesn't work with frameworks like Nativescript which support NPM modules but only if they are without DOM dependencies

**Comment by seeekr** [comment]
@dragGH102, you might be interested in this fork:

https://github.com/seeekr/ddp-client

Let me know if that works for you! One caveat: OAuth support is not in there for now, though it should be trivial to add it back in.

**Comment by dragGH102** [comment]
Thanks @seeekr . I found similar projects but didn't try that specific one.
I will check it out. For now I close the issue.
